# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/PreferencesDialogUI.ui'
#
# Created by: PyQt5 UI code generator 5.5.2-snapshot-5b5f0fb1b3f6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Preferences(object):
    def setupUi(self, Preferences):
        Preferences.setObjectName("Preferences")
        Preferences.resize(402, 258)
        Preferences.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Preferences)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBoxToninoDisplay = QtWidgets.QGroupBox(Preferences)
        self.groupBoxToninoDisplay.setObjectName("groupBoxToninoDisplay")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBoxToninoDisplay)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.dim_label = QtWidgets.QLabel(self.groupBoxToninoDisplay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dim_label.sizePolicy().hasHeightForWidth())
        self.dim_label.setSizePolicy(sizePolicy)
        self.dim_label.setMinimumSize(QtCore.QSize(60, 0))
        self.dim_label.setMaximumSize(QtCore.QSize(60, 16777215))
        self.dim_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dim_label.setObjectName("dim_label")
        self.horizontalLayout.addWidget(self.dim_label)
        self.displaySlider = QtWidgets.QSlider(self.groupBoxToninoDisplay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displaySlider.sizePolicy().hasHeightForWidth())
        self.displaySlider.setSizePolicy(sizePolicy)
        self.displaySlider.setMinimumSize(QtCore.QSize(150, 22))
        self.displaySlider.setMaximumSize(QtCore.QSize(150, 22))
        self.displaySlider.setMinimum(0)
        self.displaySlider.setMaximum(15)
        self.displaySlider.setPageStep(5)
        self.displaySlider.setProperty("value", 0)
        self.displaySlider.setTracking(False)
        self.displaySlider.setOrientation(QtCore.Qt.Horizontal)
        self.displaySlider.setObjectName("displaySlider")
        self.horizontalLayout.addWidget(self.displaySlider)
        self.bright_label = QtWidgets.QLabel(self.groupBoxToninoDisplay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bright_label.sizePolicy().hasHeightForWidth())
        self.bright_label.setSizePolicy(sizePolicy)
        self.bright_label.setMinimumSize(QtCore.QSize(60, 0))
        self.bright_label.setMaximumSize(QtCore.QSize(60, 16777215))
        self.bright_label.setObjectName("bright_label")
        self.horizontalLayout.addWidget(self.bright_label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.groupBoxToninoDisplay)
        self.groupBoxToninoTarget = QtWidgets.QGroupBox(Preferences)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxToninoTarget.sizePolicy().hasHeightForWidth())
        self.groupBoxToninoTarget.setSizePolicy(sizePolicy)
        self.groupBoxToninoTarget.setMinimumSize(QtCore.QSize(0, 120))
        self.groupBoxToninoTarget.setBaseSize(QtCore.QSize(0, 0))
        self.groupBoxToninoTarget.setObjectName("groupBoxToninoTarget")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBoxToninoTarget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 29, 361, 78))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBoxTargetValue = QtWidgets.QGroupBox(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxTargetValue.sizePolicy().hasHeightForWidth())
        self.groupBoxTargetValue.setSizePolicy(sizePolicy)
        self.groupBoxTargetValue.setMinimumSize(QtCore.QSize(0, 30))
        self.groupBoxTargetValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBoxTargetValue.setObjectName("groupBoxTargetValue")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBoxTargetValue)
        self.gridLayout.setObjectName("gridLayout")
        self.targetValueSpinBox = QtWidgets.QSpinBox(self.groupBoxTargetValue)
        self.targetValueSpinBox.setMinimumSize(QtCore.QSize(0, 22))
        self.targetValueSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.targetValueSpinBox.setMaximum(200)
        self.targetValueSpinBox.setSingleStep(0)
        self.targetValueSpinBox.setObjectName("targetValueSpinBox")
        self.gridLayout.addWidget(self.targetValueSpinBox, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.groupBoxTargetValue)
        self.groupBoxTargetRange = QtWidgets.QGroupBox(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxTargetRange.sizePolicy().hasHeightForWidth())
        self.groupBoxTargetRange.setSizePolicy(sizePolicy)
        self.groupBoxTargetRange.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBoxTargetRange.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBoxTargetRange.setObjectName("groupBoxTargetRange")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBoxTargetRange)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.range_min_label = QtWidgets.QLabel(self.groupBoxTargetRange)
        self.range_min_label.setObjectName("range_min_label")
        self.horizontalLayout_2.addWidget(self.range_min_label)
        self.rangeSlider = QtWidgets.QSlider(self.groupBoxTargetRange)
        self.rangeSlider.setMinimumSize(QtCore.QSize(0, 22))
        self.rangeSlider.setMaximum(10)
        self.rangeSlider.setPageStep(2)
        self.rangeSlider.setProperty("value", 0)
        self.rangeSlider.setTracking(False)
        self.rangeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.rangeSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.rangeSlider.setTickInterval(1)
        self.rangeSlider.setObjectName("rangeSlider")
        self.horizontalLayout_2.addWidget(self.rangeSlider)
        self.range_max_label = QtWidgets.QLabel(self.groupBoxTargetRange)
        self.range_max_label.setObjectName("range_max_label")
        self.horizontalLayout_2.addWidget(self.range_max_label)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addWidget(self.groupBoxTargetRange)
        self.verticalLayout.addWidget(self.groupBoxToninoTarget)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.buttonBox = QtWidgets.QDialogButtonBox(Preferences)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Preferences)
        QtCore.QMetaObject.connectSlotsByName(Preferences)

    def retranslateUi(self, Preferences):
        _translate = QtCore.QCoreApplication.translate
        Preferences.setWindowTitle(_translate("Preferences", "Preferences"))
        self.groupBoxToninoDisplay.setTitle(_translate("Preferences", "Tonino Display"))
        self.dim_label.setText(_translate("Preferences", "dim"))
        self.bright_label.setText(_translate("Preferences", "bright"))
        self.groupBoxToninoTarget.setTitle(_translate("Preferences", "Target"))
        self.groupBoxTargetValue.setTitle(_translate("Preferences", "Value"))
        self.groupBoxTargetRange.setTitle(_translate("Preferences", "Range"))
        self.range_min_label.setText(_translate("Preferences", "0"))
        self.range_max_label.setText(_translate("Preferences", "10"))

from . import icons_rc
