#!/bin/sh

pylupdate6 lib help \
      -ts translations/tonino_de.ts \
      -ts translations/tonino_es.ts \
      -ts translations/tonino_fr.ts \
      -ts translations/tonino_it.ts \
      -ts translations/tonino_nl.ts